sms_settings:
 UserName: mcs47chd 
 Password: MCS47CHD?123 
 Type: Bulk
 Mask: MCSCHD
 host_url: http://www.smsgatewaycenter.com/library/send_sms_2.php
 UserNameKey: UserName
 PasswordKey: Password
 TypeKey: Type
 MaskKey: Mask
 Tokey: To
 MessageKey: Message