require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AssessmentIndicatorsController do

  # This should return the minimal set of attributes required to create a valid
  # AssessmentIndicator. As you add validations to AssessmentIndicator, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all assessment_indicators as @assessment_indicators" do
      assessment_indicator = AssessmentIndicator.create! valid_attributes
      get :index
      assigns(:assessment_indicators).should eq([assessment_indicator])
    end
  end

  describe "GET show" do
    it "assigns the requested assessment_indicator as @assessment_indicator" do
      assessment_indicator = AssessmentIndicator.create! valid_attributes
      get :show, :id => assessment_indicator.id
      assigns(:assessment_indicator).should eq(assessment_indicator)
    end
  end

  describe "GET new" do
    it "assigns a new assessment_indicator as @assessment_indicator" do
      get :new
      assigns(:assessment_indicator).should be_a_new(AssessmentIndicator)
    end
  end

  describe "GET edit" do
    it "assigns the requested assessment_indicator as @assessment_indicator" do
      assessment_indicator = AssessmentIndicator.create! valid_attributes
      get :edit, :id => assessment_indicator.id
      assigns(:assessment_indicator).should eq(assessment_indicator)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AssessmentIndicator" do
        expect {
          post :create, :assessment_indicator => valid_attributes
        }.to change(AssessmentIndicator, :count).by(1)
      end

      it "assigns a newly created assessment_indicator as @assessment_indicator" do
        post :create, :assessment_indicator => valid_attributes
        assigns(:assessment_indicator).should be_a(AssessmentIndicator)
        assigns(:assessment_indicator).should be_persisted
      end

      it "redirects to the created assessment_indicator" do
        post :create, :assessment_indicator => valid_attributes
        response.should redirect_to(AssessmentIndicator.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved assessment_indicator as @assessment_indicator" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssessmentIndicator.any_instance.stub(:save).and_return(false)
        post :create, :assessment_indicator => {}
        assigns(:assessment_indicator).should be_a_new(AssessmentIndicator)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssessmentIndicator.any_instance.stub(:save).and_return(false)
        post :create, :assessment_indicator => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested assessment_indicator" do
        assessment_indicator = AssessmentIndicator.create! valid_attributes
        # Assuming there are no other assessment_indicators in the database, this
        # specifies that the AssessmentIndicator created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AssessmentIndicator.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => assessment_indicator.id, :assessment_indicator => {'these' => 'params'}
      end

      it "assigns the requested assessment_indicator as @assessment_indicator" do
        assessment_indicator = AssessmentIndicator.create! valid_attributes
        put :update, :id => assessment_indicator.id, :assessment_indicator => valid_attributes
        assigns(:assessment_indicator).should eq(assessment_indicator)
      end

      it "redirects to the assessment_indicator" do
        assessment_indicator = AssessmentIndicator.create! valid_attributes
        put :update, :id => assessment_indicator.id, :assessment_indicator => valid_attributes
        response.should redirect_to(assessment_indicator)
      end
    end

    describe "with invalid params" do
      it "assigns the assessment_indicator as @assessment_indicator" do
        assessment_indicator = AssessmentIndicator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssessmentIndicator.any_instance.stub(:save).and_return(false)
        put :update, :id => assessment_indicator.id, :assessment_indicator => {}
        assigns(:assessment_indicator).should eq(assessment_indicator)
      end

      it "re-renders the 'edit' template" do
        assessment_indicator = AssessmentIndicator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssessmentIndicator.any_instance.stub(:save).and_return(false)
        put :update, :id => assessment_indicator.id, :assessment_indicator => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested assessment_indicator" do
      assessment_indicator = AssessmentIndicator.create! valid_attributes
      expect {
        delete :destroy, :id => assessment_indicator.id
      }.to change(AssessmentIndicator, :count).by(-1)
    end

    it "redirects to the assessment_indicators list" do
      assessment_indicator = AssessmentIndicator.create! valid_attributes
      delete :destroy, :id => assessment_indicator.id
      response.should redirect_to(assessment_indicators_url)
    end
  end

end
