require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CoScholasticActivitiesController do

  # This should return the minimal set of attributes required to create a valid
  # CoScholasticActivity. As you add validations to CoScholasticActivity, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all co_scholastic_activities as @co_scholastic_activities" do
      co_scholastic_activity = CoScholasticActivity.create! valid_attributes
      get :index
      assigns(:co_scholastic_activities).should eq([co_scholastic_activity])
    end
  end

  describe "GET show" do
    it "assigns the requested co_scholastic_activity as @co_scholastic_activity" do
      co_scholastic_activity = CoScholasticActivity.create! valid_attributes
      get :show, :id => co_scholastic_activity.id
      assigns(:co_scholastic_activity).should eq(co_scholastic_activity)
    end
  end

  describe "GET new" do
    it "assigns a new co_scholastic_activity as @co_scholastic_activity" do
      get :new
      assigns(:co_scholastic_activity).should be_a_new(CoScholasticActivity)
    end
  end

  describe "GET edit" do
    it "assigns the requested co_scholastic_activity as @co_scholastic_activity" do
      co_scholastic_activity = CoScholasticActivity.create! valid_attributes
      get :edit, :id => co_scholastic_activity.id
      assigns(:co_scholastic_activity).should eq(co_scholastic_activity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CoScholasticActivity" do
        expect {
          post :create, :co_scholastic_activity => valid_attributes
        }.to change(CoScholasticActivity, :count).by(1)
      end

      it "assigns a newly created co_scholastic_activity as @co_scholastic_activity" do
        post :create, :co_scholastic_activity => valid_attributes
        assigns(:co_scholastic_activity).should be_a(CoScholasticActivity)
        assigns(:co_scholastic_activity).should be_persisted
      end

      it "redirects to the created co_scholastic_activity" do
        post :create, :co_scholastic_activity => valid_attributes
        response.should redirect_to(CoScholasticActivity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved co_scholastic_activity as @co_scholastic_activity" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoScholasticActivity.any_instance.stub(:save).and_return(false)
        post :create, :co_scholastic_activity => {}
        assigns(:co_scholastic_activity).should be_a_new(CoScholasticActivity)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CoScholasticActivity.any_instance.stub(:save).and_return(false)
        post :create, :co_scholastic_activity => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested co_scholastic_activity" do
        co_scholastic_activity = CoScholasticActivity.create! valid_attributes
        # Assuming there are no other co_scholastic_activities in the database, this
        # specifies that the CoScholasticActivity created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CoScholasticActivity.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => co_scholastic_activity.id, :co_scholastic_activity => {'these' => 'params'}
      end

      it "assigns the requested co_scholastic_activity as @co_scholastic_activity" do
        co_scholastic_activity = CoScholasticActivity.create! valid_attributes
        put :update, :id => co_scholastic_activity.id, :co_scholastic_activity => valid_attributes
        assigns(:co_scholastic_activity).should eq(co_scholastic_activity)
      end

      it "redirects to the co_scholastic_activity" do
        co_scholastic_activity = CoScholasticActivity.create! valid_attributes
        put :update, :id => co_scholastic_activity.id, :co_scholastic_activity => valid_attributes
        response.should redirect_to(co_scholastic_activity)
      end
    end

    describe "with invalid params" do
      it "assigns the co_scholastic_activity as @co_scholastic_activity" do
        co_scholastic_activity = CoScholasticActivity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoScholasticActivity.any_instance.stub(:save).and_return(false)
        put :update, :id => co_scholastic_activity.id, :co_scholastic_activity => {}
        assigns(:co_scholastic_activity).should eq(co_scholastic_activity)
      end

      it "re-renders the 'edit' template" do
        co_scholastic_activity = CoScholasticActivity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CoScholasticActivity.any_instance.stub(:save).and_return(false)
        put :update, :id => co_scholastic_activity.id, :co_scholastic_activity => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested co_scholastic_activity" do
      co_scholastic_activity = CoScholasticActivity.create! valid_attributes
      expect {
        delete :destroy, :id => co_scholastic_activity.id
      }.to change(CoScholasticActivity, :count).by(-1)
    end

    it "redirects to the co_scholastic_activities list" do
      co_scholastic_activity = CoScholasticActivity.create! valid_attributes
      delete :destroy, :id => co_scholastic_activity.id
      response.should redirect_to(co_scholastic_activities_url)
    end
  end

end
