require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EmployeeConstraintsController do

  # This should return the minimal set of attributes required to create a valid
  # EmployeeConstraint. As you add validations to EmployeeConstraint, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all employee_constraints as @employee_constraints" do
      employee_constraint = EmployeeConstraint.create! valid_attributes
      get :index
      assigns(:employee_constraints).should eq([employee_constraint])
    end
  end

  describe "GET show" do
    it "assigns the requested employee_constraint as @employee_constraint" do
      employee_constraint = EmployeeConstraint.create! valid_attributes
      get :show, :id => employee_constraint.id
      assigns(:employee_constraint).should eq(employee_constraint)
    end
  end

  describe "GET new" do
    it "assigns a new employee_constraint as @employee_constraint" do
      get :new
      assigns(:employee_constraint).should be_a_new(EmployeeConstraint)
    end
  end

  describe "GET edit" do
    it "assigns the requested employee_constraint as @employee_constraint" do
      employee_constraint = EmployeeConstraint.create! valid_attributes
      get :edit, :id => employee_constraint.id
      assigns(:employee_constraint).should eq(employee_constraint)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EmployeeConstraint" do
        expect {
          post :create, :employee_constraint => valid_attributes
        }.to change(EmployeeConstraint, :count).by(1)
      end

      it "assigns a newly created employee_constraint as @employee_constraint" do
        post :create, :employee_constraint => valid_attributes
        assigns(:employee_constraint).should be_a(EmployeeConstraint)
        assigns(:employee_constraint).should be_persisted
      end

      it "redirects to the created employee_constraint" do
        post :create, :employee_constraint => valid_attributes
        response.should redirect_to(EmployeeConstraint.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved employee_constraint as @employee_constraint" do
        # Trigger the behavior that occurs when invalid params are submitted
        EmployeeConstraint.any_instance.stub(:save).and_return(false)
        post :create, :employee_constraint => {}
        assigns(:employee_constraint).should be_a_new(EmployeeConstraint)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EmployeeConstraint.any_instance.stub(:save).and_return(false)
        post :create, :employee_constraint => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested employee_constraint" do
        employee_constraint = EmployeeConstraint.create! valid_attributes
        # Assuming there are no other employee_constraints in the database, this
        # specifies that the EmployeeConstraint created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EmployeeConstraint.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => employee_constraint.id, :employee_constraint => {'these' => 'params'}
      end

      it "assigns the requested employee_constraint as @employee_constraint" do
        employee_constraint = EmployeeConstraint.create! valid_attributes
        put :update, :id => employee_constraint.id, :employee_constraint => valid_attributes
        assigns(:employee_constraint).should eq(employee_constraint)
      end

      it "redirects to the employee_constraint" do
        employee_constraint = EmployeeConstraint.create! valid_attributes
        put :update, :id => employee_constraint.id, :employee_constraint => valid_attributes
        response.should redirect_to(employee_constraint)
      end
    end

    describe "with invalid params" do
      it "assigns the employee_constraint as @employee_constraint" do
        employee_constraint = EmployeeConstraint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EmployeeConstraint.any_instance.stub(:save).and_return(false)
        put :update, :id => employee_constraint.id, :employee_constraint => {}
        assigns(:employee_constraint).should eq(employee_constraint)
      end

      it "re-renders the 'edit' template" do
        employee_constraint = EmployeeConstraint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EmployeeConstraint.any_instance.stub(:save).and_return(false)
        put :update, :id => employee_constraint.id, :employee_constraint => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested employee_constraint" do
      employee_constraint = EmployeeConstraint.create! valid_attributes
      expect {
        delete :destroy, :id => employee_constraint.id
      }.to change(EmployeeConstraint, :count).by(-1)
    end

    it "redirects to the employee_constraints list" do
      employee_constraint = EmployeeConstraint.create! valid_attributes
      delete :destroy, :id => employee_constraint.id
      response.should redirect_to(employee_constraints_url)
    end
  end

end
