require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExamGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # ExamGroup. As you add validations to ExamGroup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all exam_groups as @exam_groups" do
      exam_group = ExamGroup.create! valid_attributes
      get :index
      assigns(:exam_groups).should eq([exam_group])
    end
  end

  describe "GET show" do
    it "assigns the requested exam_group as @exam_group" do
      exam_group = ExamGroup.create! valid_attributes
      get :show, :id => exam_group.id
      assigns(:exam_group).should eq(exam_group)
    end
  end

  describe "GET new" do
    it "assigns a new exam_group as @exam_group" do
      get :new
      assigns(:exam_group).should be_a_new(ExamGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested exam_group as @exam_group" do
      exam_group = ExamGroup.create! valid_attributes
      get :edit, :id => exam_group.id
      assigns(:exam_group).should eq(exam_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ExamGroup" do
        expect {
          post :create, :exam_group => valid_attributes
        }.to change(ExamGroup, :count).by(1)
      end

      it "assigns a newly created exam_group as @exam_group" do
        post :create, :exam_group => valid_attributes
        assigns(:exam_group).should be_a(ExamGroup)
        assigns(:exam_group).should be_persisted
      end

      it "redirects to the created exam_group" do
        post :create, :exam_group => valid_attributes
        response.should redirect_to(ExamGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved exam_group as @exam_group" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExamGroup.any_instance.stub(:save).and_return(false)
        post :create, :exam_group => {}
        assigns(:exam_group).should be_a_new(ExamGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExamGroup.any_instance.stub(:save).and_return(false)
        post :create, :exam_group => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested exam_group" do
        exam_group = ExamGroup.create! valid_attributes
        # Assuming there are no other exam_groups in the database, this
        # specifies that the ExamGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ExamGroup.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => exam_group.id, :exam_group => {'these' => 'params'}
      end

      it "assigns the requested exam_group as @exam_group" do
        exam_group = ExamGroup.create! valid_attributes
        put :update, :id => exam_group.id, :exam_group => valid_attributes
        assigns(:exam_group).should eq(exam_group)
      end

      it "redirects to the exam_group" do
        exam_group = ExamGroup.create! valid_attributes
        put :update, :id => exam_group.id, :exam_group => valid_attributes
        response.should redirect_to(exam_group)
      end
    end

    describe "with invalid params" do
      it "assigns the exam_group as @exam_group" do
        exam_group = ExamGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExamGroup.any_instance.stub(:save).and_return(false)
        put :update, :id => exam_group.id, :exam_group => {}
        assigns(:exam_group).should eq(exam_group)
      end

      it "re-renders the 'edit' template" do
        exam_group = ExamGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExamGroup.any_instance.stub(:save).and_return(false)
        put :update, :id => exam_group.id, :exam_group => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested exam_group" do
      exam_group = ExamGroup.create! valid_attributes
      expect {
        delete :destroy, :id => exam_group.id
      }.to change(ExamGroup, :count).by(-1)
    end

    it "redirects to the exam_groups list" do
      exam_group = ExamGroup.create! valid_attributes
      delete :destroy, :id => exam_group.id
      response.should redirect_to(exam_groups_url)
    end
  end

end
