require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HostelDetailsController do

  # This should return the minimal set of attributes required to create a valid
  # HostelDetail. As you add validations to HostelDetail, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all hostel_details as @hostel_details" do
      hostel_detail = HostelDetail.create! valid_attributes
      get :index
      assigns(:hostel_details).should eq([hostel_detail])
    end
  end

  describe "GET show" do
    it "assigns the requested hostel_detail as @hostel_detail" do
      hostel_detail = HostelDetail.create! valid_attributes
      get :show, :id => hostel_detail.id
      assigns(:hostel_detail).should eq(hostel_detail)
    end
  end

  describe "GET new" do
    it "assigns a new hostel_detail as @hostel_detail" do
      get :new
      assigns(:hostel_detail).should be_a_new(HostelDetail)
    end
  end

  describe "GET edit" do
    it "assigns the requested hostel_detail as @hostel_detail" do
      hostel_detail = HostelDetail.create! valid_attributes
      get :edit, :id => hostel_detail.id
      assigns(:hostel_detail).should eq(hostel_detail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HostelDetail" do
        expect {
          post :create, :hostel_detail => valid_attributes
        }.to change(HostelDetail, :count).by(1)
      end

      it "assigns a newly created hostel_detail as @hostel_detail" do
        post :create, :hostel_detail => valid_attributes
        assigns(:hostel_detail).should be_a(HostelDetail)
        assigns(:hostel_detail).should be_persisted
      end

      it "redirects to the created hostel_detail" do
        post :create, :hostel_detail => valid_attributes
        response.should redirect_to(HostelDetail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hostel_detail as @hostel_detail" do
        # Trigger the behavior that occurs when invalid params are submitted
        HostelDetail.any_instance.stub(:save).and_return(false)
        post :create, :hostel_detail => {}
        assigns(:hostel_detail).should be_a_new(HostelDetail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HostelDetail.any_instance.stub(:save).and_return(false)
        post :create, :hostel_detail => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hostel_detail" do
        hostel_detail = HostelDetail.create! valid_attributes
        # Assuming there are no other hostel_details in the database, this
        # specifies that the HostelDetail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HostelDetail.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => hostel_detail.id, :hostel_detail => {'these' => 'params'}
      end

      it "assigns the requested hostel_detail as @hostel_detail" do
        hostel_detail = HostelDetail.create! valid_attributes
        put :update, :id => hostel_detail.id, :hostel_detail => valid_attributes
        assigns(:hostel_detail).should eq(hostel_detail)
      end

      it "redirects to the hostel_detail" do
        hostel_detail = HostelDetail.create! valid_attributes
        put :update, :id => hostel_detail.id, :hostel_detail => valid_attributes
        response.should redirect_to(hostel_detail)
      end
    end

    describe "with invalid params" do
      it "assigns the hostel_detail as @hostel_detail" do
        hostel_detail = HostelDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HostelDetail.any_instance.stub(:save).and_return(false)
        put :update, :id => hostel_detail.id, :hostel_detail => {}
        assigns(:hostel_detail).should eq(hostel_detail)
      end

      it "re-renders the 'edit' template" do
        hostel_detail = HostelDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HostelDetail.any_instance.stub(:save).and_return(false)
        put :update, :id => hostel_detail.id, :hostel_detail => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hostel_detail" do
      hostel_detail = HostelDetail.create! valid_attributes
      expect {
        delete :destroy, :id => hostel_detail.id
      }.to change(HostelDetail, :count).by(-1)
    end

    it "redirects to the hostel_details list" do
      hostel_detail = HostelDetail.create! valid_attributes
      delete :destroy, :id => hostel_detail.id
      response.should redirect_to(hostel_details_url)
    end
  end

end
