require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InstantFeesController do

  # This should return the minimal set of attributes required to create a valid
  # InstantFee. As you add validations to InstantFee, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all instant_fees as @instant_fees" do
      instant_fee = InstantFee.create! valid_attributes
      get :index
      assigns(:instant_fees).should eq([instant_fee])
    end
  end

  describe "GET show" do
    it "assigns the requested instant_fee as @instant_fee" do
      instant_fee = InstantFee.create! valid_attributes
      get :show, :id => instant_fee.id
      assigns(:instant_fee).should eq(instant_fee)
    end
  end

  describe "GET new" do
    it "assigns a new instant_fee as @instant_fee" do
      get :new
      assigns(:instant_fee).should be_a_new(InstantFee)
    end
  end

  describe "GET edit" do
    it "assigns the requested instant_fee as @instant_fee" do
      instant_fee = InstantFee.create! valid_attributes
      get :edit, :id => instant_fee.id
      assigns(:instant_fee).should eq(instant_fee)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InstantFee" do
        expect {
          post :create, :instant_fee => valid_attributes
        }.to change(InstantFee, :count).by(1)
      end

      it "assigns a newly created instant_fee as @instant_fee" do
        post :create, :instant_fee => valid_attributes
        assigns(:instant_fee).should be_a(InstantFee)
        assigns(:instant_fee).should be_persisted
      end

      it "redirects to the created instant_fee" do
        post :create, :instant_fee => valid_attributes
        response.should redirect_to(InstantFee.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved instant_fee as @instant_fee" do
        # Trigger the behavior that occurs when invalid params are submitted
        InstantFee.any_instance.stub(:save).and_return(false)
        post :create, :instant_fee => {}
        assigns(:instant_fee).should be_a_new(InstantFee)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InstantFee.any_instance.stub(:save).and_return(false)
        post :create, :instant_fee => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested instant_fee" do
        instant_fee = InstantFee.create! valid_attributes
        # Assuming there are no other instant_fees in the database, this
        # specifies that the InstantFee created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InstantFee.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => instant_fee.id, :instant_fee => {'these' => 'params'}
      end

      it "assigns the requested instant_fee as @instant_fee" do
        instant_fee = InstantFee.create! valid_attributes
        put :update, :id => instant_fee.id, :instant_fee => valid_attributes
        assigns(:instant_fee).should eq(instant_fee)
      end

      it "redirects to the instant_fee" do
        instant_fee = InstantFee.create! valid_attributes
        put :update, :id => instant_fee.id, :instant_fee => valid_attributes
        response.should redirect_to(instant_fee)
      end
    end

    describe "with invalid params" do
      it "assigns the instant_fee as @instant_fee" do
        instant_fee = InstantFee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InstantFee.any_instance.stub(:save).and_return(false)
        put :update, :id => instant_fee.id, :instant_fee => {}
        assigns(:instant_fee).should eq(instant_fee)
      end

      it "re-renders the 'edit' template" do
        instant_fee = InstantFee.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InstantFee.any_instance.stub(:save).and_return(false)
        put :update, :id => instant_fee.id, :instant_fee => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested instant_fee" do
      instant_fee = InstantFee.create! valid_attributes
      expect {
        delete :destroy, :id => instant_fee.id
      }.to change(InstantFee, :count).by(-1)
    end

    it "redirects to the instant_fees list" do
      instant_fee = InstantFee.create! valid_attributes
      delete :destroy, :id => instant_fee.id
      response.should redirect_to(instant_fees_url)
    end
  end

end
