require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InstantFeeParticularsController do

  # This should return the minimal set of attributes required to create a valid
  # InstantFeeParticular. As you add validations to InstantFeeParticular, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all instant_fee_particulars as @instant_fee_particulars" do
      instant_fee_particular = InstantFeeParticular.create! valid_attributes
      get :index
      assigns(:instant_fee_particulars).should eq([instant_fee_particular])
    end
  end

  describe "GET show" do
    it "assigns the requested instant_fee_particular as @instant_fee_particular" do
      instant_fee_particular = InstantFeeParticular.create! valid_attributes
      get :show, :id => instant_fee_particular.id
      assigns(:instant_fee_particular).should eq(instant_fee_particular)
    end
  end

  describe "GET new" do
    it "assigns a new instant_fee_particular as @instant_fee_particular" do
      get :new
      assigns(:instant_fee_particular).should be_a_new(InstantFeeParticular)
    end
  end

  describe "GET edit" do
    it "assigns the requested instant_fee_particular as @instant_fee_particular" do
      instant_fee_particular = InstantFeeParticular.create! valid_attributes
      get :edit, :id => instant_fee_particular.id
      assigns(:instant_fee_particular).should eq(instant_fee_particular)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InstantFeeParticular" do
        expect {
          post :create, :instant_fee_particular => valid_attributes
        }.to change(InstantFeeParticular, :count).by(1)
      end

      it "assigns a newly created instant_fee_particular as @instant_fee_particular" do
        post :create, :instant_fee_particular => valid_attributes
        assigns(:instant_fee_particular).should be_a(InstantFeeParticular)
        assigns(:instant_fee_particular).should be_persisted
      end

      it "redirects to the created instant_fee_particular" do
        post :create, :instant_fee_particular => valid_attributes
        response.should redirect_to(InstantFeeParticular.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved instant_fee_particular as @instant_fee_particular" do
        # Trigger the behavior that occurs when invalid params are submitted
        InstantFeeParticular.any_instance.stub(:save).and_return(false)
        post :create, :instant_fee_particular => {}
        assigns(:instant_fee_particular).should be_a_new(InstantFeeParticular)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InstantFeeParticular.any_instance.stub(:save).and_return(false)
        post :create, :instant_fee_particular => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested instant_fee_particular" do
        instant_fee_particular = InstantFeeParticular.create! valid_attributes
        # Assuming there are no other instant_fee_particulars in the database, this
        # specifies that the InstantFeeParticular created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InstantFeeParticular.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => instant_fee_particular.id, :instant_fee_particular => {'these' => 'params'}
      end

      it "assigns the requested instant_fee_particular as @instant_fee_particular" do
        instant_fee_particular = InstantFeeParticular.create! valid_attributes
        put :update, :id => instant_fee_particular.id, :instant_fee_particular => valid_attributes
        assigns(:instant_fee_particular).should eq(instant_fee_particular)
      end

      it "redirects to the instant_fee_particular" do
        instant_fee_particular = InstantFeeParticular.create! valid_attributes
        put :update, :id => instant_fee_particular.id, :instant_fee_particular => valid_attributes
        response.should redirect_to(instant_fee_particular)
      end
    end

    describe "with invalid params" do
      it "assigns the instant_fee_particular as @instant_fee_particular" do
        instant_fee_particular = InstantFeeParticular.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InstantFeeParticular.any_instance.stub(:save).and_return(false)
        put :update, :id => instant_fee_particular.id, :instant_fee_particular => {}
        assigns(:instant_fee_particular).should eq(instant_fee_particular)
      end

      it "re-renders the 'edit' template" do
        instant_fee_particular = InstantFeeParticular.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InstantFeeParticular.any_instance.stub(:save).and_return(false)
        put :update, :id => instant_fee_particular.id, :instant_fee_particular => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested instant_fee_particular" do
      instant_fee_particular = InstantFeeParticular.create! valid_attributes
      expect {
        delete :destroy, :id => instant_fee_particular.id
      }.to change(InstantFeeParticular, :count).by(-1)
    end

    it "redirects to the instant_fee_particulars list" do
      instant_fee_particular = InstantFeeParticular.create! valid_attributes
      delete :destroy, :id => instant_fee_particular.id
      response.should redirect_to(instant_fee_particulars_url)
    end
  end

end
