require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PassengerBoardTransportDetailsController do

  # This should return the minimal set of attributes required to create a valid
  # PassengerBoardTransportDetail. As you add validations to PassengerBoardTransportDetail, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all passenger_board_transport_details as @passenger_board_transport_details" do
      passenger_board_transport_detail = PassengerBoardTransportDetail.create! valid_attributes
      get :index
      assigns(:passenger_board_transport_details).should eq([passenger_board_transport_detail])
    end
  end

  describe "GET show" do
    it "assigns the requested passenger_board_transport_detail as @passenger_board_transport_detail" do
      passenger_board_transport_detail = PassengerBoardTransportDetail.create! valid_attributes
      get :show, :id => passenger_board_transport_detail.id
      assigns(:passenger_board_transport_detail).should eq(passenger_board_transport_detail)
    end
  end

  describe "GET new" do
    it "assigns a new passenger_board_transport_detail as @passenger_board_transport_detail" do
      get :new
      assigns(:passenger_board_transport_detail).should be_a_new(PassengerBoardTransportDetail)
    end
  end

  describe "GET edit" do
    it "assigns the requested passenger_board_transport_detail as @passenger_board_transport_detail" do
      passenger_board_transport_detail = PassengerBoardTransportDetail.create! valid_attributes
      get :edit, :id => passenger_board_transport_detail.id
      assigns(:passenger_board_transport_detail).should eq(passenger_board_transport_detail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PassengerBoardTransportDetail" do
        expect {
          post :create, :passenger_board_transport_detail => valid_attributes
        }.to change(PassengerBoardTransportDetail, :count).by(1)
      end

      it "assigns a newly created passenger_board_transport_detail as @passenger_board_transport_detail" do
        post :create, :passenger_board_transport_detail => valid_attributes
        assigns(:passenger_board_transport_detail).should be_a(PassengerBoardTransportDetail)
        assigns(:passenger_board_transport_detail).should be_persisted
      end

      it "redirects to the created passenger_board_transport_detail" do
        post :create, :passenger_board_transport_detail => valid_attributes
        response.should redirect_to(PassengerBoardTransportDetail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved passenger_board_transport_detail as @passenger_board_transport_detail" do
        # Trigger the behavior that occurs when invalid params are submitted
        PassengerBoardTransportDetail.any_instance.stub(:save).and_return(false)
        post :create, :passenger_board_transport_detail => {}
        assigns(:passenger_board_transport_detail).should be_a_new(PassengerBoardTransportDetail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PassengerBoardTransportDetail.any_instance.stub(:save).and_return(false)
        post :create, :passenger_board_transport_detail => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested passenger_board_transport_detail" do
        passenger_board_transport_detail = PassengerBoardTransportDetail.create! valid_attributes
        # Assuming there are no other passenger_board_transport_details in the database, this
        # specifies that the PassengerBoardTransportDetail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PassengerBoardTransportDetail.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => passenger_board_transport_detail.id, :passenger_board_transport_detail => {'these' => 'params'}
      end

      it "assigns the requested passenger_board_transport_detail as @passenger_board_transport_detail" do
        passenger_board_transport_detail = PassengerBoardTransportDetail.create! valid_attributes
        put :update, :id => passenger_board_transport_detail.id, :passenger_board_transport_detail => valid_attributes
        assigns(:passenger_board_transport_detail).should eq(passenger_board_transport_detail)
      end

      it "redirects to the passenger_board_transport_detail" do
        passenger_board_transport_detail = PassengerBoardTransportDetail.create! valid_attributes
        put :update, :id => passenger_board_transport_detail.id, :passenger_board_transport_detail => valid_attributes
        response.should redirect_to(passenger_board_transport_detail)
      end
    end

    describe "with invalid params" do
      it "assigns the passenger_board_transport_detail as @passenger_board_transport_detail" do
        passenger_board_transport_detail = PassengerBoardTransportDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PassengerBoardTransportDetail.any_instance.stub(:save).and_return(false)
        put :update, :id => passenger_board_transport_detail.id, :passenger_board_transport_detail => {}
        assigns(:passenger_board_transport_detail).should eq(passenger_board_transport_detail)
      end

      it "re-renders the 'edit' template" do
        passenger_board_transport_detail = PassengerBoardTransportDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PassengerBoardTransportDetail.any_instance.stub(:save).and_return(false)
        put :update, :id => passenger_board_transport_detail.id, :passenger_board_transport_detail => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested passenger_board_transport_detail" do
      passenger_board_transport_detail = PassengerBoardTransportDetail.create! valid_attributes
      expect {
        delete :destroy, :id => passenger_board_transport_detail.id
      }.to change(PassengerBoardTransportDetail, :count).by(-1)
    end

    it "redirects to the passenger_board_transport_details list" do
      passenger_board_transport_detail = PassengerBoardTransportDetail.create! valid_attributes
      delete :destroy, :id => passenger_board_transport_detail.id
      response.should redirect_to(passenger_board_transport_details_url)
    end
  end

end
