require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PtmMastersController do

  # This should return the minimal set of attributes required to create a valid
  # PtmMaster. As you add validations to PtmMaster, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all ptm_masters as @ptm_masters" do
      ptm_master = PtmMaster.create! valid_attributes
      get :index
      assigns(:ptm_masters).should eq([ptm_master])
    end
  end

  describe "GET show" do
    it "assigns the requested ptm_master as @ptm_master" do
      ptm_master = PtmMaster.create! valid_attributes
      get :show, :id => ptm_master.id
      assigns(:ptm_master).should eq(ptm_master)
    end
  end

  describe "GET new" do
    it "assigns a new ptm_master as @ptm_master" do
      get :new
      assigns(:ptm_master).should be_a_new(PtmMaster)
    end
  end

  describe "GET edit" do
    it "assigns the requested ptm_master as @ptm_master" do
      ptm_master = PtmMaster.create! valid_attributes
      get :edit, :id => ptm_master.id
      assigns(:ptm_master).should eq(ptm_master)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PtmMaster" do
        expect {
          post :create, :ptm_master => valid_attributes
        }.to change(PtmMaster, :count).by(1)
      end

      it "assigns a newly created ptm_master as @ptm_master" do
        post :create, :ptm_master => valid_attributes
        assigns(:ptm_master).should be_a(PtmMaster)
        assigns(:ptm_master).should be_persisted
      end

      it "redirects to the created ptm_master" do
        post :create, :ptm_master => valid_attributes
        response.should redirect_to(PtmMaster.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ptm_master as @ptm_master" do
        # Trigger the behavior that occurs when invalid params are submitted
        PtmMaster.any_instance.stub(:save).and_return(false)
        post :create, :ptm_master => {}
        assigns(:ptm_master).should be_a_new(PtmMaster)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PtmMaster.any_instance.stub(:save).and_return(false)
        post :create, :ptm_master => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ptm_master" do
        ptm_master = PtmMaster.create! valid_attributes
        # Assuming there are no other ptm_masters in the database, this
        # specifies that the PtmMaster created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PtmMaster.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => ptm_master.id, :ptm_master => {'these' => 'params'}
      end

      it "assigns the requested ptm_master as @ptm_master" do
        ptm_master = PtmMaster.create! valid_attributes
        put :update, :id => ptm_master.id, :ptm_master => valid_attributes
        assigns(:ptm_master).should eq(ptm_master)
      end

      it "redirects to the ptm_master" do
        ptm_master = PtmMaster.create! valid_attributes
        put :update, :id => ptm_master.id, :ptm_master => valid_attributes
        response.should redirect_to(ptm_master)
      end
    end

    describe "with invalid params" do
      it "assigns the ptm_master as @ptm_master" do
        ptm_master = PtmMaster.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PtmMaster.any_instance.stub(:save).and_return(false)
        put :update, :id => ptm_master.id, :ptm_master => {}
        assigns(:ptm_master).should eq(ptm_master)
      end

      it "re-renders the 'edit' template" do
        ptm_master = PtmMaster.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PtmMaster.any_instance.stub(:save).and_return(false)
        put :update, :id => ptm_master.id, :ptm_master => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ptm_master" do
      ptm_master = PtmMaster.create! valid_attributes
      expect {
        delete :destroy, :id => ptm_master.id
      }.to change(PtmMaster, :count).by(-1)
    end

    it "redirects to the ptm_masters list" do
      ptm_master = PtmMaster.create! valid_attributes
      delete :destroy, :id => ptm_master.id
      response.should redirect_to(ptm_masters_url)
    end
  end

end
