require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PtmDetailsController do

  # This should return the minimal set of attributes required to create a valid
  # PtmDetail. As you add validations to PtmDetail, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all ptm_details as @ptm_details" do
      ptm_detail = PtmDetail.create! valid_attributes
      get :index
      assigns(:ptm_details).should eq([ptm_detail])
    end
  end

  describe "GET show" do
    it "assigns the requested ptm_detail as @ptm_detail" do
      ptm_detail = PtmDetail.create! valid_attributes
      get :show, :id => ptm_detail.id
      assigns(:ptm_detail).should eq(ptm_detail)
    end
  end

  describe "GET new" do
    it "assigns a new ptm_detail as @ptm_detail" do
      get :new
      assigns(:ptm_detail).should be_a_new(PtmDetail)
    end
  end

  describe "GET edit" do
    it "assigns the requested ptm_detail as @ptm_detail" do
      ptm_detail = PtmDetail.create! valid_attributes
      get :edit, :id => ptm_detail.id
      assigns(:ptm_detail).should eq(ptm_detail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PtmDetail" do
        expect {
          post :create, :ptm_detail => valid_attributes
        }.to change(PtmDetail, :count).by(1)
      end

      it "assigns a newly created ptm_detail as @ptm_detail" do
        post :create, :ptm_detail => valid_attributes
        assigns(:ptm_detail).should be_a(PtmDetail)
        assigns(:ptm_detail).should be_persisted
      end

      it "redirects to the created ptm_detail" do
        post :create, :ptm_detail => valid_attributes
        response.should redirect_to(PtmDetail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ptm_detail as @ptm_detail" do
        # Trigger the behavior that occurs when invalid params are submitted
        PtmDetail.any_instance.stub(:save).and_return(false)
        post :create, :ptm_detail => {}
        assigns(:ptm_detail).should be_a_new(PtmDetail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PtmDetail.any_instance.stub(:save).and_return(false)
        post :create, :ptm_detail => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ptm_detail" do
        ptm_detail = PtmDetail.create! valid_attributes
        # Assuming there are no other ptm_details in the database, this
        # specifies that the PtmDetail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PtmDetail.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => ptm_detail.id, :ptm_detail => {'these' => 'params'}
      end

      it "assigns the requested ptm_detail as @ptm_detail" do
        ptm_detail = PtmDetail.create! valid_attributes
        put :update, :id => ptm_detail.id, :ptm_detail => valid_attributes
        assigns(:ptm_detail).should eq(ptm_detail)
      end

      it "redirects to the ptm_detail" do
        ptm_detail = PtmDetail.create! valid_attributes
        put :update, :id => ptm_detail.id, :ptm_detail => valid_attributes
        response.should redirect_to(ptm_detail)
      end
    end

    describe "with invalid params" do
      it "assigns the ptm_detail as @ptm_detail" do
        ptm_detail = PtmDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PtmDetail.any_instance.stub(:save).and_return(false)
        put :update, :id => ptm_detail.id, :ptm_detail => {}
        assigns(:ptm_detail).should eq(ptm_detail)
      end

      it "re-renders the 'edit' template" do
        ptm_detail = PtmDetail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PtmDetail.any_instance.stub(:save).and_return(false)
        put :update, :id => ptm_detail.id, :ptm_detail => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ptm_detail" do
      ptm_detail = PtmDetail.create! valid_attributes
      expect {
        delete :destroy, :id => ptm_detail.id
      }.to change(PtmDetail, :count).by(-1)
    end

    it "redirects to the ptm_details list" do
      ptm_detail = PtmDetail.create! valid_attributes
      delete :destroy, :id => ptm_detail.id
      response.should redirect_to(ptm_details_url)
    end
  end

end
