require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RoomConstraintsController do

  # This should return the minimal set of attributes required to create a valid
  # RoomConstraint. As you add validations to RoomConstraint, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all room_constraints as @room_constraints" do
      room_constraint = RoomConstraint.create! valid_attributes
      get :index
      assigns(:room_constraints).should eq([room_constraint])
    end
  end

  describe "GET show" do
    it "assigns the requested room_constraint as @room_constraint" do
      room_constraint = RoomConstraint.create! valid_attributes
      get :show, :id => room_constraint.id
      assigns(:room_constraint).should eq(room_constraint)
    end
  end

  describe "GET new" do
    it "assigns a new room_constraint as @room_constraint" do
      get :new
      assigns(:room_constraint).should be_a_new(RoomConstraint)
    end
  end

  describe "GET edit" do
    it "assigns the requested room_constraint as @room_constraint" do
      room_constraint = RoomConstraint.create! valid_attributes
      get :edit, :id => room_constraint.id
      assigns(:room_constraint).should eq(room_constraint)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RoomConstraint" do
        expect {
          post :create, :room_constraint => valid_attributes
        }.to change(RoomConstraint, :count).by(1)
      end

      it "assigns a newly created room_constraint as @room_constraint" do
        post :create, :room_constraint => valid_attributes
        assigns(:room_constraint).should be_a(RoomConstraint)
        assigns(:room_constraint).should be_persisted
      end

      it "redirects to the created room_constraint" do
        post :create, :room_constraint => valid_attributes
        response.should redirect_to(RoomConstraint.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved room_constraint as @room_constraint" do
        # Trigger the behavior that occurs when invalid params are submitted
        RoomConstraint.any_instance.stub(:save).and_return(false)
        post :create, :room_constraint => {}
        assigns(:room_constraint).should be_a_new(RoomConstraint)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RoomConstraint.any_instance.stub(:save).and_return(false)
        post :create, :room_constraint => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested room_constraint" do
        room_constraint = RoomConstraint.create! valid_attributes
        # Assuming there are no other room_constraints in the database, this
        # specifies that the RoomConstraint created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RoomConstraint.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => room_constraint.id, :room_constraint => {'these' => 'params'}
      end

      it "assigns the requested room_constraint as @room_constraint" do
        room_constraint = RoomConstraint.create! valid_attributes
        put :update, :id => room_constraint.id, :room_constraint => valid_attributes
        assigns(:room_constraint).should eq(room_constraint)
      end

      it "redirects to the room_constraint" do
        room_constraint = RoomConstraint.create! valid_attributes
        put :update, :id => room_constraint.id, :room_constraint => valid_attributes
        response.should redirect_to(room_constraint)
      end
    end

    describe "with invalid params" do
      it "assigns the room_constraint as @room_constraint" do
        room_constraint = RoomConstraint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RoomConstraint.any_instance.stub(:save).and_return(false)
        put :update, :id => room_constraint.id, :room_constraint => {}
        assigns(:room_constraint).should eq(room_constraint)
      end

      it "re-renders the 'edit' template" do
        room_constraint = RoomConstraint.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RoomConstraint.any_instance.stub(:save).and_return(false)
        put :update, :id => room_constraint.id, :room_constraint => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested room_constraint" do
      room_constraint = RoomConstraint.create! valid_attributes
      expect {
        delete :destroy, :id => room_constraint.id
      }.to change(RoomConstraint, :count).by(-1)
    end

    it "redirects to the room_constraints list" do
      room_constraint = RoomConstraint.create! valid_attributes
      delete :destroy, :id => room_constraint.id
      response.should redirect_to(room_constraints_url)
    end
  end

end
