require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SchoolSessionsController do

  # This should return the minimal set of attributes required to create a valid
  # SchoolSession. As you add validations to SchoolSession, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all school_sessions as @school_sessions" do
      school_session = SchoolSession.create! valid_attributes
      get :index
      assigns(:school_sessions).should eq([school_session])
    end
  end

  describe "GET show" do
    it "assigns the requested school_session as @school_session" do
      school_session = SchoolSession.create! valid_attributes
      get :show, :id => school_session.id
      assigns(:school_session).should eq(school_session)
    end
  end

  describe "GET new" do
    it "assigns a new school_session as @school_session" do
      get :new
      assigns(:school_session).should be_a_new(SchoolSession)
    end
  end

  describe "GET edit" do
    it "assigns the requested school_session as @school_session" do
      school_session = SchoolSession.create! valid_attributes
      get :edit, :id => school_session.id
      assigns(:school_session).should eq(school_session)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SchoolSession" do
        expect {
          post :create, :school_session => valid_attributes
        }.to change(SchoolSession, :count).by(1)
      end

      it "assigns a newly created school_session as @school_session" do
        post :create, :school_session => valid_attributes
        assigns(:school_session).should be_a(SchoolSession)
        assigns(:school_session).should be_persisted
      end

      it "redirects to the created school_session" do
        post :create, :school_session => valid_attributes
        response.should redirect_to(SchoolSession.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved school_session as @school_session" do
        # Trigger the behavior that occurs when invalid params are submitted
        SchoolSession.any_instance.stub(:save).and_return(false)
        post :create, :school_session => {}
        assigns(:school_session).should be_a_new(SchoolSession)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SchoolSession.any_instance.stub(:save).and_return(false)
        post :create, :school_session => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested school_session" do
        school_session = SchoolSession.create! valid_attributes
        # Assuming there are no other school_sessions in the database, this
        # specifies that the SchoolSession created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SchoolSession.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => school_session.id, :school_session => {'these' => 'params'}
      end

      it "assigns the requested school_session as @school_session" do
        school_session = SchoolSession.create! valid_attributes
        put :update, :id => school_session.id, :school_session => valid_attributes
        assigns(:school_session).should eq(school_session)
      end

      it "redirects to the school_session" do
        school_session = SchoolSession.create! valid_attributes
        put :update, :id => school_session.id, :school_session => valid_attributes
        response.should redirect_to(school_session)
      end
    end

    describe "with invalid params" do
      it "assigns the school_session as @school_session" do
        school_session = SchoolSession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SchoolSession.any_instance.stub(:save).and_return(false)
        put :update, :id => school_session.id, :school_session => {}
        assigns(:school_session).should eq(school_session)
      end

      it "re-renders the 'edit' template" do
        school_session = SchoolSession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SchoolSession.any_instance.stub(:save).and_return(false)
        put :update, :id => school_session.id, :school_session => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested school_session" do
      school_session = SchoolSession.create! valid_attributes
      expect {
        delete :destroy, :id => school_session.id
      }.to change(SchoolSession, :count).by(-1)
    end

    it "redirects to the school_sessions list" do
      school_session = SchoolSession.create! valid_attributes
      delete :destroy, :id => school_session.id
      response.should redirect_to(school_sessions_url)
    end
  end

end
