require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StudentCoScholasticAssessmentsController do

  # This should return the minimal set of attributes required to create a valid
  # StudentCoScholasticAssessment. As you add validations to StudentCoScholasticAssessment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all student_co_scholastic_assessments as @student_co_scholastic_assessments" do
      student_co_scholastic_assessment = StudentCoScholasticAssessment.create! valid_attributes
      get :index
      assigns(:student_co_scholastic_assessments).should eq([student_co_scholastic_assessment])
    end
  end

  describe "GET show" do
    it "assigns the requested student_co_scholastic_assessment as @student_co_scholastic_assessment" do
      student_co_scholastic_assessment = StudentCoScholasticAssessment.create! valid_attributes
      get :show, :id => student_co_scholastic_assessment.id
      assigns(:student_co_scholastic_assessment).should eq(student_co_scholastic_assessment)
    end
  end

  describe "GET new" do
    it "assigns a new student_co_scholastic_assessment as @student_co_scholastic_assessment" do
      get :new
      assigns(:student_co_scholastic_assessment).should be_a_new(StudentCoScholasticAssessment)
    end
  end

  describe "GET edit" do
    it "assigns the requested student_co_scholastic_assessment as @student_co_scholastic_assessment" do
      student_co_scholastic_assessment = StudentCoScholasticAssessment.create! valid_attributes
      get :edit, :id => student_co_scholastic_assessment.id
      assigns(:student_co_scholastic_assessment).should eq(student_co_scholastic_assessment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StudentCoScholasticAssessment" do
        expect {
          post :create, :student_co_scholastic_assessment => valid_attributes
        }.to change(StudentCoScholasticAssessment, :count).by(1)
      end

      it "assigns a newly created student_co_scholastic_assessment as @student_co_scholastic_assessment" do
        post :create, :student_co_scholastic_assessment => valid_attributes
        assigns(:student_co_scholastic_assessment).should be_a(StudentCoScholasticAssessment)
        assigns(:student_co_scholastic_assessment).should be_persisted
      end

      it "redirects to the created student_co_scholastic_assessment" do
        post :create, :student_co_scholastic_assessment => valid_attributes
        response.should redirect_to(StudentCoScholasticAssessment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved student_co_scholastic_assessment as @student_co_scholastic_assessment" do
        # Trigger the behavior that occurs when invalid params are submitted
        StudentCoScholasticAssessment.any_instance.stub(:save).and_return(false)
        post :create, :student_co_scholastic_assessment => {}
        assigns(:student_co_scholastic_assessment).should be_a_new(StudentCoScholasticAssessment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StudentCoScholasticAssessment.any_instance.stub(:save).and_return(false)
        post :create, :student_co_scholastic_assessment => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested student_co_scholastic_assessment" do
        student_co_scholastic_assessment = StudentCoScholasticAssessment.create! valid_attributes
        # Assuming there are no other student_co_scholastic_assessments in the database, this
        # specifies that the StudentCoScholasticAssessment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StudentCoScholasticAssessment.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => student_co_scholastic_assessment.id, :student_co_scholastic_assessment => {'these' => 'params'}
      end

      it "assigns the requested student_co_scholastic_assessment as @student_co_scholastic_assessment" do
        student_co_scholastic_assessment = StudentCoScholasticAssessment.create! valid_attributes
        put :update, :id => student_co_scholastic_assessment.id, :student_co_scholastic_assessment => valid_attributes
        assigns(:student_co_scholastic_assessment).should eq(student_co_scholastic_assessment)
      end

      it "redirects to the student_co_scholastic_assessment" do
        student_co_scholastic_assessment = StudentCoScholasticAssessment.create! valid_attributes
        put :update, :id => student_co_scholastic_assessment.id, :student_co_scholastic_assessment => valid_attributes
        response.should redirect_to(student_co_scholastic_assessment)
      end
    end

    describe "with invalid params" do
      it "assigns the student_co_scholastic_assessment as @student_co_scholastic_assessment" do
        student_co_scholastic_assessment = StudentCoScholasticAssessment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StudentCoScholasticAssessment.any_instance.stub(:save).and_return(false)
        put :update, :id => student_co_scholastic_assessment.id, :student_co_scholastic_assessment => {}
        assigns(:student_co_scholastic_assessment).should eq(student_co_scholastic_assessment)
      end

      it "re-renders the 'edit' template" do
        student_co_scholastic_assessment = StudentCoScholasticAssessment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StudentCoScholasticAssessment.any_instance.stub(:save).and_return(false)
        put :update, :id => student_co_scholastic_assessment.id, :student_co_scholastic_assessment => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested student_co_scholastic_assessment" do
      student_co_scholastic_assessment = StudentCoScholasticAssessment.create! valid_attributes
      expect {
        delete :destroy, :id => student_co_scholastic_assessment.id
      }.to change(StudentCoScholasticAssessment, :count).by(-1)
    end

    it "redirects to the student_co_scholastic_assessments list" do
      student_co_scholastic_assessment = StudentCoScholasticAssessment.create! valid_attributes
      delete :destroy, :id => student_co_scholastic_assessment.id
      response.should redirect_to(student_co_scholastic_assessments_url)
    end
  end

end
