require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SubSkillsController do

  # This should return the minimal set of attributes required to create a valid
  # SubSkill. As you add validations to SubSkill, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all sub_skills as @sub_skills" do
      sub_skill = SubSkill.create! valid_attributes
      get :index
      assigns(:sub_skills).should eq([sub_skill])
    end
  end

  describe "GET show" do
    it "assigns the requested sub_skill as @sub_skill" do
      sub_skill = SubSkill.create! valid_attributes
      get :show, :id => sub_skill.id
      assigns(:sub_skill).should eq(sub_skill)
    end
  end

  describe "GET new" do
    it "assigns a new sub_skill as @sub_skill" do
      get :new
      assigns(:sub_skill).should be_a_new(SubSkill)
    end
  end

  describe "GET edit" do
    it "assigns the requested sub_skill as @sub_skill" do
      sub_skill = SubSkill.create! valid_attributes
      get :edit, :id => sub_skill.id
      assigns(:sub_skill).should eq(sub_skill)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SubSkill" do
        expect {
          post :create, :sub_skill => valid_attributes
        }.to change(SubSkill, :count).by(1)
      end

      it "assigns a newly created sub_skill as @sub_skill" do
        post :create, :sub_skill => valid_attributes
        assigns(:sub_skill).should be_a(SubSkill)
        assigns(:sub_skill).should be_persisted
      end

      it "redirects to the created sub_skill" do
        post :create, :sub_skill => valid_attributes
        response.should redirect_to(SubSkill.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sub_skill as @sub_skill" do
        # Trigger the behavior that occurs when invalid params are submitted
        SubSkill.any_instance.stub(:save).and_return(false)
        post :create, :sub_skill => {}
        assigns(:sub_skill).should be_a_new(SubSkill)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SubSkill.any_instance.stub(:save).and_return(false)
        post :create, :sub_skill => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sub_skill" do
        sub_skill = SubSkill.create! valid_attributes
        # Assuming there are no other sub_skills in the database, this
        # specifies that the SubSkill created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SubSkill.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => sub_skill.id, :sub_skill => {'these' => 'params'}
      end

      it "assigns the requested sub_skill as @sub_skill" do
        sub_skill = SubSkill.create! valid_attributes
        put :update, :id => sub_skill.id, :sub_skill => valid_attributes
        assigns(:sub_skill).should eq(sub_skill)
      end

      it "redirects to the sub_skill" do
        sub_skill = SubSkill.create! valid_attributes
        put :update, :id => sub_skill.id, :sub_skill => valid_attributes
        response.should redirect_to(sub_skill)
      end
    end

    describe "with invalid params" do
      it "assigns the sub_skill as @sub_skill" do
        sub_skill = SubSkill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SubSkill.any_instance.stub(:save).and_return(false)
        put :update, :id => sub_skill.id, :sub_skill => {}
        assigns(:sub_skill).should eq(sub_skill)
      end

      it "re-renders the 'edit' template" do
        sub_skill = SubSkill.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SubSkill.any_instance.stub(:save).and_return(false)
        put :update, :id => sub_skill.id, :sub_skill => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sub_skill" do
      sub_skill = SubSkill.create! valid_attributes
      expect {
        delete :destroy, :id => sub_skill.id
      }.to change(SubSkill, :count).by(-1)
    end

    it "redirects to the sub_skills list" do
      sub_skill = SubSkill.create! valid_attributes
      delete :destroy, :id => sub_skill.id
      response.should redirect_to(sub_skills_url)
    end
  end

end
