require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TeacherDiariesController do

  # This should return the minimal set of attributes required to create a valid
  # TeacherDiary. As you add validations to TeacherDiary, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all teacher_diaries as @teacher_diaries" do
      teacher_diary = TeacherDiary.create! valid_attributes
      get :index
      assigns(:teacher_diaries).should eq([teacher_diary])
    end
  end

  describe "GET show" do
    it "assigns the requested teacher_diary as @teacher_diary" do
      teacher_diary = TeacherDiary.create! valid_attributes
      get :show, :id => teacher_diary.id
      assigns(:teacher_diary).should eq(teacher_diary)
    end
  end

  describe "GET new" do
    it "assigns a new teacher_diary as @teacher_diary" do
      get :new
      assigns(:teacher_diary).should be_a_new(TeacherDiary)
    end
  end

  describe "GET edit" do
    it "assigns the requested teacher_diary as @teacher_diary" do
      teacher_diary = TeacherDiary.create! valid_attributes
      get :edit, :id => teacher_diary.id
      assigns(:teacher_diary).should eq(teacher_diary)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TeacherDiary" do
        expect {
          post :create, :teacher_diary => valid_attributes
        }.to change(TeacherDiary, :count).by(1)
      end

      it "assigns a newly created teacher_diary as @teacher_diary" do
        post :create, :teacher_diary => valid_attributes
        assigns(:teacher_diary).should be_a(TeacherDiary)
        assigns(:teacher_diary).should be_persisted
      end

      it "redirects to the created teacher_diary" do
        post :create, :teacher_diary => valid_attributes
        response.should redirect_to(TeacherDiary.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved teacher_diary as @teacher_diary" do
        # Trigger the behavior that occurs when invalid params are submitted
        TeacherDiary.any_instance.stub(:save).and_return(false)
        post :create, :teacher_diary => {}
        assigns(:teacher_diary).should be_a_new(TeacherDiary)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TeacherDiary.any_instance.stub(:save).and_return(false)
        post :create, :teacher_diary => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested teacher_diary" do
        teacher_diary = TeacherDiary.create! valid_attributes
        # Assuming there are no other teacher_diaries in the database, this
        # specifies that the TeacherDiary created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TeacherDiary.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => teacher_diary.id, :teacher_diary => {'these' => 'params'}
      end

      it "assigns the requested teacher_diary as @teacher_diary" do
        teacher_diary = TeacherDiary.create! valid_attributes
        put :update, :id => teacher_diary.id, :teacher_diary => valid_attributes
        assigns(:teacher_diary).should eq(teacher_diary)
      end

      it "redirects to the teacher_diary" do
        teacher_diary = TeacherDiary.create! valid_attributes
        put :update, :id => teacher_diary.id, :teacher_diary => valid_attributes
        response.should redirect_to(teacher_diary)
      end
    end

    describe "with invalid params" do
      it "assigns the teacher_diary as @teacher_diary" do
        teacher_diary = TeacherDiary.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TeacherDiary.any_instance.stub(:save).and_return(false)
        put :update, :id => teacher_diary.id, :teacher_diary => {}
        assigns(:teacher_diary).should eq(teacher_diary)
      end

      it "re-renders the 'edit' template" do
        teacher_diary = TeacherDiary.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TeacherDiary.any_instance.stub(:save).and_return(false)
        put :update, :id => teacher_diary.id, :teacher_diary => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested teacher_diary" do
      teacher_diary = TeacherDiary.create! valid_attributes
      expect {
        delete :destroy, :id => teacher_diary.id
      }.to change(TeacherDiary, :count).by(-1)
    end

    it "redirects to the teacher_diaries list" do
      teacher_diary = TeacherDiary.create! valid_attributes
      delete :destroy, :id => teacher_diary.id
      response.should redirect_to(teacher_diaries_url)
    end
  end

end
