require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TransportBoardsController do

  # This should return the minimal set of attributes required to create a valid
  # TransportBoard. As you add validations to TransportBoard, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all transport_boards as @transport_boards" do
      transport_board = TransportBoard.create! valid_attributes
      get :index
      assigns(:transport_boards).should eq([transport_board])
    end
  end

  describe "GET show" do
    it "assigns the requested transport_board as @transport_board" do
      transport_board = TransportBoard.create! valid_attributes
      get :show, :id => transport_board.id
      assigns(:transport_board).should eq(transport_board)
    end
  end

  describe "GET new" do
    it "assigns a new transport_board as @transport_board" do
      get :new
      assigns(:transport_board).should be_a_new(TransportBoard)
    end
  end

  describe "GET edit" do
    it "assigns the requested transport_board as @transport_board" do
      transport_board = TransportBoard.create! valid_attributes
      get :edit, :id => transport_board.id
      assigns(:transport_board).should eq(transport_board)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TransportBoard" do
        expect {
          post :create, :transport_board => valid_attributes
        }.to change(TransportBoard, :count).by(1)
      end

      it "assigns a newly created transport_board as @transport_board" do
        post :create, :transport_board => valid_attributes
        assigns(:transport_board).should be_a(TransportBoard)
        assigns(:transport_board).should be_persisted
      end

      it "redirects to the created transport_board" do
        post :create, :transport_board => valid_attributes
        response.should redirect_to(TransportBoard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved transport_board as @transport_board" do
        # Trigger the behavior that occurs when invalid params are submitted
        TransportBoard.any_instance.stub(:save).and_return(false)
        post :create, :transport_board => {}
        assigns(:transport_board).should be_a_new(TransportBoard)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TransportBoard.any_instance.stub(:save).and_return(false)
        post :create, :transport_board => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested transport_board" do
        transport_board = TransportBoard.create! valid_attributes
        # Assuming there are no other transport_boards in the database, this
        # specifies that the TransportBoard created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TransportBoard.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => transport_board.id, :transport_board => {'these' => 'params'}
      end

      it "assigns the requested transport_board as @transport_board" do
        transport_board = TransportBoard.create! valid_attributes
        put :update, :id => transport_board.id, :transport_board => valid_attributes
        assigns(:transport_board).should eq(transport_board)
      end

      it "redirects to the transport_board" do
        transport_board = TransportBoard.create! valid_attributes
        put :update, :id => transport_board.id, :transport_board => valid_attributes
        response.should redirect_to(transport_board)
      end
    end

    describe "with invalid params" do
      it "assigns the transport_board as @transport_board" do
        transport_board = TransportBoard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TransportBoard.any_instance.stub(:save).and_return(false)
        put :update, :id => transport_board.id, :transport_board => {}
        assigns(:transport_board).should eq(transport_board)
      end

      it "re-renders the 'edit' template" do
        transport_board = TransportBoard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TransportBoard.any_instance.stub(:save).and_return(false)
        put :update, :id => transport_board.id, :transport_board => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested transport_board" do
      transport_board = TransportBoard.create! valid_attributes
      expect {
        delete :destroy, :id => transport_board.id
      }.to change(TransportBoard, :count).by(-1)
    end

    it "redirects to the transport_boards list" do
      transport_board = TransportBoard.create! valid_attributes
      delete :destroy, :id => transport_board.id
      response.should redirect_to(transport_boards_url)
    end
  end

end
