require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TransportFeeCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # TransportFeeCategory. As you add validations to TransportFeeCategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all transport_fee_categories as @transport_fee_categories" do
      transport_fee_category = TransportFeeCategory.create! valid_attributes
      get :index
      assigns(:transport_fee_categories).should eq([transport_fee_category])
    end
  end

  describe "GET show" do
    it "assigns the requested transport_fee_category as @transport_fee_category" do
      transport_fee_category = TransportFeeCategory.create! valid_attributes
      get :show, :id => transport_fee_category.id
      assigns(:transport_fee_category).should eq(transport_fee_category)
    end
  end

  describe "GET new" do
    it "assigns a new transport_fee_category as @transport_fee_category" do
      get :new
      assigns(:transport_fee_category).should be_a_new(TransportFeeCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested transport_fee_category as @transport_fee_category" do
      transport_fee_category = TransportFeeCategory.create! valid_attributes
      get :edit, :id => transport_fee_category.id
      assigns(:transport_fee_category).should eq(transport_fee_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TransportFeeCategory" do
        expect {
          post :create, :transport_fee_category => valid_attributes
        }.to change(TransportFeeCategory, :count).by(1)
      end

      it "assigns a newly created transport_fee_category as @transport_fee_category" do
        post :create, :transport_fee_category => valid_attributes
        assigns(:transport_fee_category).should be_a(TransportFeeCategory)
        assigns(:transport_fee_category).should be_persisted
      end

      it "redirects to the created transport_fee_category" do
        post :create, :transport_fee_category => valid_attributes
        response.should redirect_to(TransportFeeCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved transport_fee_category as @transport_fee_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        TransportFeeCategory.any_instance.stub(:save).and_return(false)
        post :create, :transport_fee_category => {}
        assigns(:transport_fee_category).should be_a_new(TransportFeeCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TransportFeeCategory.any_instance.stub(:save).and_return(false)
        post :create, :transport_fee_category => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested transport_fee_category" do
        transport_fee_category = TransportFeeCategory.create! valid_attributes
        # Assuming there are no other transport_fee_categories in the database, this
        # specifies that the TransportFeeCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TransportFeeCategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => transport_fee_category.id, :transport_fee_category => {'these' => 'params'}
      end

      it "assigns the requested transport_fee_category as @transport_fee_category" do
        transport_fee_category = TransportFeeCategory.create! valid_attributes
        put :update, :id => transport_fee_category.id, :transport_fee_category => valid_attributes
        assigns(:transport_fee_category).should eq(transport_fee_category)
      end

      it "redirects to the transport_fee_category" do
        transport_fee_category = TransportFeeCategory.create! valid_attributes
        put :update, :id => transport_fee_category.id, :transport_fee_category => valid_attributes
        response.should redirect_to(transport_fee_category)
      end
    end

    describe "with invalid params" do
      it "assigns the transport_fee_category as @transport_fee_category" do
        transport_fee_category = TransportFeeCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TransportFeeCategory.any_instance.stub(:save).and_return(false)
        put :update, :id => transport_fee_category.id, :transport_fee_category => {}
        assigns(:transport_fee_category).should eq(transport_fee_category)
      end

      it "re-renders the 'edit' template" do
        transport_fee_category = TransportFeeCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TransportFeeCategory.any_instance.stub(:save).and_return(false)
        put :update, :id => transport_fee_category.id, :transport_fee_category => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested transport_fee_category" do
      transport_fee_category = TransportFeeCategory.create! valid_attributes
      expect {
        delete :destroy, :id => transport_fee_category.id
      }.to change(TransportFeeCategory, :count).by(-1)
    end

    it "redirects to the transport_fee_categories list" do
      transport_fee_category = TransportFeeCategory.create! valid_attributes
      delete :destroy, :id => transport_fee_category.id
      response.should redirect_to(transport_fee_categories_url)
    end
  end

end
