require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TransportVehiclesController do

  # This should return the minimal set of attributes required to create a valid
  # TransportVehicle. As you add validations to TransportVehicle, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all transport_vehicles as @transport_vehicles" do
      transport_vehicle = TransportVehicle.create! valid_attributes
      get :index
      assigns(:transport_vehicles).should eq([transport_vehicle])
    end
  end

  describe "GET show" do
    it "assigns the requested transport_vehicle as @transport_vehicle" do
      transport_vehicle = TransportVehicle.create! valid_attributes
      get :show, :id => transport_vehicle.id
      assigns(:transport_vehicle).should eq(transport_vehicle)
    end
  end

  describe "GET new" do
    it "assigns a new transport_vehicle as @transport_vehicle" do
      get :new
      assigns(:transport_vehicle).should be_a_new(TransportVehicle)
    end
  end

  describe "GET edit" do
    it "assigns the requested transport_vehicle as @transport_vehicle" do
      transport_vehicle = TransportVehicle.create! valid_attributes
      get :edit, :id => transport_vehicle.id
      assigns(:transport_vehicle).should eq(transport_vehicle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TransportVehicle" do
        expect {
          post :create, :transport_vehicle => valid_attributes
        }.to change(TransportVehicle, :count).by(1)
      end

      it "assigns a newly created transport_vehicle as @transport_vehicle" do
        post :create, :transport_vehicle => valid_attributes
        assigns(:transport_vehicle).should be_a(TransportVehicle)
        assigns(:transport_vehicle).should be_persisted
      end

      it "redirects to the created transport_vehicle" do
        post :create, :transport_vehicle => valid_attributes
        response.should redirect_to(TransportVehicle.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved transport_vehicle as @transport_vehicle" do
        # Trigger the behavior that occurs when invalid params are submitted
        TransportVehicle.any_instance.stub(:save).and_return(false)
        post :create, :transport_vehicle => {}
        assigns(:transport_vehicle).should be_a_new(TransportVehicle)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TransportVehicle.any_instance.stub(:save).and_return(false)
        post :create, :transport_vehicle => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested transport_vehicle" do
        transport_vehicle = TransportVehicle.create! valid_attributes
        # Assuming there are no other transport_vehicles in the database, this
        # specifies that the TransportVehicle created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TransportVehicle.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => transport_vehicle.id, :transport_vehicle => {'these' => 'params'}
      end

      it "assigns the requested transport_vehicle as @transport_vehicle" do
        transport_vehicle = TransportVehicle.create! valid_attributes
        put :update, :id => transport_vehicle.id, :transport_vehicle => valid_attributes
        assigns(:transport_vehicle).should eq(transport_vehicle)
      end

      it "redirects to the transport_vehicle" do
        transport_vehicle = TransportVehicle.create! valid_attributes
        put :update, :id => transport_vehicle.id, :transport_vehicle => valid_attributes
        response.should redirect_to(transport_vehicle)
      end
    end

    describe "with invalid params" do
      it "assigns the transport_vehicle as @transport_vehicle" do
        transport_vehicle = TransportVehicle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TransportVehicle.any_instance.stub(:save).and_return(false)
        put :update, :id => transport_vehicle.id, :transport_vehicle => {}
        assigns(:transport_vehicle).should eq(transport_vehicle)
      end

      it "re-renders the 'edit' template" do
        transport_vehicle = TransportVehicle.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TransportVehicle.any_instance.stub(:save).and_return(false)
        put :update, :id => transport_vehicle.id, :transport_vehicle => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested transport_vehicle" do
      transport_vehicle = TransportVehicle.create! valid_attributes
      expect {
        delete :destroy, :id => transport_vehicle.id
      }.to change(TransportVehicle, :count).by(-1)
    end

    it "redirects to the transport_vehicles list" do
      transport_vehicle = TransportVehicle.create! valid_attributes
      delete :destroy, :id => transport_vehicle.id
      response.should redirect_to(transport_vehicles_url)
    end
  end

end
